### ISSUE TITLE
any chance to participate in this workshop? :)

### ISSUE THREAD

**Issue by serine** [aedin/PCAworkshop#6]
@aedin I've noticed a fork of this repo at @mdozmorov github it looks like you people are actively working on it and about? to run this workshop? I'd love to participate in it if it's possible and if it's via teleconf, which is likely given current env. 

As mentioned in the abstract PCA and related dimension reductionality techniques are essential in understanding sources of variability etc. Recently I have been working a lot with Hi-C (this is how I stumbled across @mdozmorov github) and I feel like I need more knowledge and skill regarding biostats to work with such data (looping calling along is doing my head in)   

Many thank in advance !

**Comment by aedin** [comment]
Would be delighted if you could join us.  The schedule of the meeting is at bioc2020.bioconductor.org and the PCA workshop is on Wednesday.  There was actually an several talks that applied PCA or multiple factor analysis on HiC at the ISMB meeting this week.  One treated the data as binary and I was interested to know if that the most appropriate form? If you want to send me an example HiC toy dataset, I could definitely add a quick example of some processing steps that might help

**Comment by serine** [comment]
Awesome ! I've registered, but the time difference is 14 hours :D , will do my best to stay awake at 3am. I think most seminars will be available on demand later.  The whole event looks pretty awesome thanks for the tipoff

Thanks for the offer, let me have a bit of think about how to generate toy dataset and what I can share. Part of the problem as you know Hi-C is ultra-deep datasets, the once that I have range from 200 - 500 G read depth, I guess I can sample down to 5 or 10%. 
The problems that I have are at several points

1. I'm not 100% sure that juicer workflow keeps all the reads in
2. I'm not 100% sure about `.hic` files and `KR` normalisation (values don't match up between reads extracted as KR norm from `.hic` file or raw reads extracted and then normalised with [KRnorm()](https://rdrr.io/bioc/HiCcompare/man/KRnorm.html) 
3. At the other spectrum [fanc](https://github.com/vaquerizaslab/fanc) gives strange looking PCA plots that doesn't make sense biologically (hence the need to figure out how to make my own PCA)
4. And we can't figure out what makes a "good" set of loops and how to check replicatability (gonna try out [HicRep](https://github.com/MonkeyLB/hicrep)

thanks!

p.s perhaps I'll send you a four small fastqs, two conditions, two replicates

**Comment by aedin** [comment]
Great, see you at the meeting.  The time difference with Australia is tough. I will look at the HiC resources you sent that you.  Are you on the Bioc community slack channel, it would be a good place to discuss this... This link should work https://join.slack.com/t/community-bioc/shared_invite/zt-g3ys3drk-hElHeQ_EndyrMmx1djFaBg
